# Generated by Django 4.2.11 on 2024-04-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_profile_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wall_picture',
            field=models.ImageField(default='media/uploads/wall_pictures/default.jpg', upload_to='media/uploads/wall_pictures'),
        ),
    ]
