# Generated by Django 5.0.4 on 2024-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_profile_wall_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='media/uploads/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wall_picture',
            field=models.ImageField(default='uploads/wall_pictures/default.jpg', upload_to='media/uploads/wall_pictures'),
        ),
    ]
